### ISSUE TITLE
Ubuntu16: Gluu-Gateway service is not starting after system reboot 

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#284]
GG service not starting automatically after system reboot. User need to start GG service manually in Ub16 case.

**Comment by ldeveloperl1985** [comment]
At the startup it failed to start **oxd** and **kong**, starting Konga(GG UI) and postgres service. User need to start oxd and kong service manually.

```
# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      886/sshd        
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      936/postgres    
tcp        0      0 0.0.0.0:1338            0.0.0.0:*               LISTEN      701/node        
tcp6       0      0 :::22                   :::*                    LISTEN      886/sshd        
tcp6       0      0 ::1:5432                :::*                    LISTEN      936/postgres 
```

**Comment by mbaser** [comment]
When I run on Ubuntu16:
`/etc/init.d/gluu-gateway restart`

GG service at port 1338 is not starting. Nothing available on log file.

**Comment by mbaser** [comment]
After a while, the log is :
```
root@gg:/var/log# cat konga.log 
No DB Adapter defined. Using localDB...
Hook:api_health_checks:process() called
Hook:health_checks:process() called
Hook:user_events_hook:process() called
Kongnode had models, so no seed needed
Emailtransport had models, so no seed needed
Error: The hook `grunt` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 60000)
    at Timeout.tooLong [as _onTimeout] (/opt/gluu-gateway/konga/node_modules/sails/lib/app/private/loadHooks.js:85:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

**Comment by mbaser** [comment]
I set timeout 120 secs and it worked. I changed line 85 of file `/opt/gluu-gateway/konga/node_modules/sails/lib/app/private/loadHooks.js`

from:
```
timeoutInterval = (sails.config[hooks[id].configKey || id] && sails.config[hooks[id].configKey || id]._hookTimeout) || sails.config.hookTimeout || 20000;
```
to:
var timeoutInterval = 120000;
